name: Controllo Interpelli ITIS Galilei

on:
  schedule:
    - cron: '*/5 * * * *'  # Esegue lo script ogni 5 minuti
  workflow_dispatch:  # Permette di avviarlo manualmente
  repository_dispatch:  # Permette di avviarlo tramite ping esterno
    types: [manual_trigger]

jobs:
  check_interpelli:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Permette al bot di fare commit e push
      actions: read  # Permette al bot di leggere le azioni

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'  # Cache dei pacchetti Python

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check and update last hash
        run: |
          if [ -f last_hash.txt ]; then
            echo "Last hash file found."
          else
            echo "Creating new last_hash.txt file."
            echo "" > last_hash.txt  # Crea il file vuoto se non esiste
          fi
          python interpelli.py
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Commit and push changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "GitHub Actions"
          git add last_hash.txt
          git commit -m "Update last_hash.txt"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa il GITHUB_TOKEN con permessi di scrittura
