name: Controllo Interpelli ITIS Galilei

on:
  schedule:
    - cron: '*/5 * * * *'  # Esegue lo script ogni 5 minuti
  workflow_dispatch:  # Permette di avviarlo manualmente
  repository_dispatch:  # Permette di avviarlo tramite ping esterno
    types: [manual_trigger]

jobs:
  check_interpelli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'  # Cache dei pacchetti Python

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python interpelli.py
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
